'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { apiClient } from '@/lib/api-client';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { InteractiveVideoPlayer, VideoActivity, formatVideoTime } from '@/components/interactive-video/interactive-video-player';
import { Plus, Trash2, Save, Sparkles } from 'lucide-react';

const types = ['MULTIPLE_CHOICE','MULTIPLE_SELECT','TRUE_FALSE','FILL_BLANK','SHORT_ANSWER','LISTENING','VOCABULARY','GRAMMAR','READING','WRITING','SPEAKING'];
const blankActivity = (timestamp = 0): VideoActivity => ({ id: '', timestampSeconds: timestamp, type: 'MULTIPLE_CHOICE', title: '', instructions: '', content: { options: ['', '', ''], correctAnswer: '' }, points: 1, required: true, allowRetry: true });

export default function InteractiveVideoEditorPage() {
  const { lessonId } = useParams<{ courseId: string; lessonId: string }>();
  const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { apiClient.get<any>(`/teacher/interactive-videos/lessons/${lessonId}`).then((v) => setData(v)).catch(() => setData({ videoUrl: '', activities: [], transcript: [] })).finally(() => setLoading(false)); }, [lessonId]);
  if (loading) return <div className="p-8 text-sm text-slate-500">Loading interactive lesson…</div>;
  const update = (key: string, value: any) => setData((v: any) => ({ ...v, [key]: value }));
  const save = async (status = data.status) => { setSaving(true); try { const v = await apiClient.put(`/teacher/interactive-videos/lessons/${lessonId}`, { ...data, status }); setData(v); setMessage(status === 'PUBLISHED' ? 'Lesson published.' : 'Draft saved.'); } catch (e: any) { setMessage(e.message); } finally { setSaving(false); } };
  const saveActivity = async (activity: VideoActivity) => { try { const saved = await apiClient.post(`/teacher/interactive-videos/lessons/${lessonId}/activities`, activity); update('activities', [...(data.activities || []).filter((a: any) => a.id !== activity.id), saved]); } catch (e: any) { setMessage(e.message); } };
  if (!data) return null;
  return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-8"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Teacher studio · interactive video</p><h1 className="mt-1 text-2xl font-bold">Build an English video lesson</h1><p className="text-sm text-slate-500">Place learning checkpoints on the timeline. Students must complete required activities before continuing.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => save('DRAFT')} isLoading={saving}><Save className="mr-2 h-4 w-4" />Save draft</Button><Button onClick={() => save('PUBLISHED')}><Sparkles className="mr-2 h-4 w-4" />Publish</Button></div></header>
    {message && <div role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}
    <Card className="grid gap-4 p-5 md:grid-cols-2"><label className="text-sm font-semibold">Video URL<input value={data.videoUrl || ''} onChange={(e) => update('videoUrl', e.target.value)} placeholder="https://… (MP4 or supported stream)" className="mt-2 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold">Thumbnail URL<input value={data.thumbnailUrl || ''} onChange={(e) => update('thumbnailUrl', e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold">CEFR level<select value={data.cefrLevel || 'A1'} onChange={(e) => update('cefrLevel', e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal">{['Pre-A1','A1','A2','B1','B2','C1','C2'].map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Navigation<select value={data.navigationMode || 'FREE'} onChange={(e) => update('navigationMode', e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"><option value="FREE">Free navigation</option><option value="GUIDED">Guided learning</option><option value="REQUIRED_COMPLETION">Required completion</option></select></label></Card>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><div><InteractiveVideoPlayer lessonId={lessonId} videoUrl={data.videoUrl || ''} durationSeconds={data.durationSeconds} navigationMode={data.navigationMode} activities={data.activities || []} transcript={data.transcript || []} /><Card className="mt-4 p-5"><h2 className="mb-3 font-bold">Transcript lines</h2><textarea value={(data.transcript || []).map((x: any) => `${x.time}|${x.text}`).join('\n')} onChange={(e) => update('transcript', e.target.value.split('\n').filter(Boolean).map((line) => { const [time, ...text] = line.split('|'); return { time: Number(time) || 0, text: text.join('|') }; }))} rows={6} placeholder="0|Hello everyone…" className="w-full rounded-xl border p-3 font-mono text-sm" /></Card></div>
      <Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Activity timeline</h2><p className="text-xs text-slate-500">{(data.activities || []).length} checkpoints</p></div><Button size="sm" onClick={() => update('activities', [...(data.activities || []), blankActivity(0)])}><Plus className="mr-1 h-4 w-4" />Add</Button></div><div className="space-y-4">{(data.activities || []).map((activity: VideoActivity, index: number) => <div key={activity.id || index} className="rounded-xl border border-slate-200 p-3"><div className="mb-2 flex items-center justify-between"><span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">{formatVideoTime(activity.timestampSeconds)}</span><button aria-label="Delete activity" onClick={async () => { if (activity.id) await apiClient.delete(`/teacher/interactive-videos/activities/${activity.id}`); update('activities', data.activities.filter((_: any, i: number) => i !== index)); }} className="text-rose-500"><Trash2 size={16} /></button></div><input value={activity.title} onChange={(e) => { const a = [...data.activities]; a[index] = { ...activity, title: e.target.value }; update('activities', a); }} placeholder="Question title" className="mb-2 w-full rounded-lg border p-2 text-sm" /><div className="grid grid-cols-2 gap-2"><input type="number" min="0" value={activity.timestampSeconds} onChange={(e) => { const a = [...data.activities]; a[index] = { ...activity, timestampSeconds: Number(e.target.value) }; update('activities', a); }} className="rounded-lg border p-2 text-sm" /><select value={activity.type} onChange={(e) => { const a = [...data.activities]; a[index] = { ...activity, type: e.target.value }; update('activities', a); }} className="rounded-lg border p-2 text-sm">{types.map((t) => <option key={t}>{t}</option>)}</select></div><label className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={activity.required} onChange={(e) => { const a = [...data.activities]; a[index] = { ...activity, required: e.target.checked }; update('activities', a); }} />Required checkpoint</label><Button size="sm" variant="secondary" className="mt-3 w-full" onClick={() => saveActivity(activity)}>Save activity</Button></div>)}</div></Card></div>
    <Card className="p-5"><h2 className="font-bold">Resources</h2><p className="mt-1 text-sm text-slate-500">Resources marked viewable are returned only to enrolled students by the protected API.</p></Card>
  </main>;
}
